import {smartLogo, quantumLogo, crosscheckLogo, logo, innoLogo} from './imgs';

export const CAREER_DATA = [
  {
    img: innoLogo,
    alt: '이노어센드',
    width: 150,
    company: '주식회사 이노어센드',
    period: '2025.8 ~ (재직중)',
    description: '오늘의 혁신이 내일의 도약으로',
    position: '직무 : Software Engineer',
    job: '주요업무 :',
    jobList: [
      '- 백엔드 / 프론트 개발',
      '- UI/UX 최적화 및 사용자 경험 개선',
      '- 기존 플랫폼 유지 및 보수',
      '- API 통합 및 관리',
      '- 서버 데이터베이스 및 보안 관리',
      '- 그 외 제반 IT 업무',
    ],
  },
  {
    img: smartLogo,
    alt: '스마트샤인',
    width: 150,
    company: '주식회사 스마트샤인',
    period: '2024.12 ~ 2025.08',
    description: '전문 인력과 스마트 기술의 결합, 완벽한 객실관리의 시작',
    position: '소속 : 본사 IT부서',
    job: '주요업무 :',
    jobList: [
      '- 백엔드 / 프론트 개발',
      '- UI/UX 최적화 및 사용자 경험 개선',
      '- 기존 플랫폼 유지 및 보수',
      '- API 통합 및 관리',
      '- 서버 데이터베이스 및 보안 관리',
      '- 그 외 제반 IT 업무',
    ],
  },
  {
    img: quantumLogo,
    alt: '퀀텀데이터',
    width: 150,
    company: '주식회사 퀀텀데이터',
    period: '2024.08 ~ 2024.10 (약 3개월)',
    description:
      '고도화된 증권 정보를 바탕으로 시장의 정보 비대칭성 해소 및 혁신을 위한 핀테크 엔터프라이즈',
    position: '소속 : 플랫폼실 백엔드 개발자',
    job: '주요업무 :',
    jobList: [
      '- 플랫폼 백엔드 아키텍처 설계 및 개발',
      '- 전반적인 API 설계 및 개발 수행',
      '- 데이터베이스 설계 및 최적화',
      '- 본인 인증 (Nice 솔루션) 도입 및 개발',
      '- 결제 (PG사) 솔루션 도입',
      '- GitHub Actions를 통한 빌드 및 배포 자동화',
      '- HTTPS 보안 설정',
    ],
  },
  {
    img: crosscheckLogo,
    company: '주식회사 크로스체크',
    width: 150,
    period: '2023.07 ~ 2024.10 (약 1년 3개월)',
    description:
      '최고의 노하우와 기술력을 기반으로 고객과 함께 성장하는 STO 전문가 집단',
    position: '소속 : 플랫폼실 백엔드 개발자',
    job: '주요업무 :',
    jobList: [
      '- 플랫폼 백엔드 아키텍처 설계 및 개발',
      '- 전반적인 API 설계 및 개발 수행',
      '- 데이터베이스 설계 및 최적화',
      '- 본인 인증 (Nice 솔루션) 도입 및 개발',
      '- 결제 (PG사) 솔루션 도입',
      '- GitHub Actions를 통한 빌드 및 배포 자동화',
      '- HTTPS 보안 설정',
    ],
  },
  {
    img: logo,
    alt: '경일게임아카데미',
    width: 200,
    company: '경일게임아카데미',
    period: '2022.08.22 ~ 2023.05.30',
    description: '블록체인 기반 핀테크 응용 SW개발자 양성과정',
    job: '훈련 우수상 수상',
  },
];
