name: portfolio
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3
      - name: Install dependencies
        run: cd nextjh && yarn install
      - name: Build
        run: cd nextjh && yarn run build
      - name: zip distributions
        run: zip -r build.zip ./nextjh/build ./nextjh/appspec.yml ./nextjs/deploy.sh
      - name: Sync Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: aws s3 cp --region ap-northeast-2 ./build.zip s3://jjhportfolio/
      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: deploy with AWS codeDeploy
        run: |
          aws deploy create-deployment \
          --application-name portfolio-deploy \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name jhfolio \
          --s3-location bucket=jjhportfolio,bundleType=zip,key=build.zip \
